version: 2.1

jobs:
  test-build:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # run build
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      # run lint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  upload-docker:
    docker:
      - image: circleci/golang:1.15

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build docker container
          command: |
            docker build --tag=$DOCKER_IMAGE_NAME . 
            docker image ls

      - run:
          name: Upload Docker to Dockerhub
          command: |
            echo "Docker ID and Image: $DOCKER_IMAGE_NAME"
            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
            docker tag $DOCKER_IMAGE_NAME $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:319523281765
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:319523281765

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yum install -y tar gzip
      - run:
          name: Ensure EKS network exists
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/network.yml \
              --tags project=${ENVIRONMENT_NAME}-project \
              --stack-name "${ENVIRONMENT_NAME}-eks-network" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://cloudformation/network-parameters.json
      - run:
          name: Ensure EKS Cluster exists
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/cluster.yml \
              --tags project=${ENVIRONMENT_NAME}-project \
              --stack-name "${ENVIRONMENT_NAME}-eks-cluster" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://cloudformation/cluster-parameters.json \
              --capabilities CAPABILITY_NAMED_IAM
          no_output_timeout: 15m
      - run:
          name: Ensure Nodegroup exists
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/nodegroup.yml \
              --tags project=${ENVIRONMENT_NAME}-project \
              --stack-name "${ENVIRONMENT_NAME}-eks-nodegroup" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://cloudformation/nodegroup-parameters.json \
              --capabilities CAPABILITY_NAMED_IAM
      - run:
          name: Ensure management instances exists
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/management.yml \
              --tags project=${ENVIRONMENT_NAME}-project \
              --stack-name "${ENVIRONMENT_NAME}-eks-management" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://cloudformation/management-parameters.json \
              --output text >> ~/project/ansible/checkIfDeployed.txt
            cat ~/project/ansible/checkIfDeployed.txt
      - run:
          name: Extract the IPs of the management instances for Ansible
          command: |
            echo [management] > ~/project/ansible/inventory.txt
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters Name=tag:Name,Values=capstone-project-management* --output text >> ~/project/ansible/inventory.txt
            cat ~/project/ansible/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/ansible/inventory.txt
            - project/ansible/checkIfDeployed.txt

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.17
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a3:83:19:0c:ff:be:6c:66:7b:9f:c4:3e:e2:d1:2e:08"
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            if grep -q "No changes to deploy" ~/project/ansible/checkIfDeployed.txt
            then
                echo "here if"
                cat ~/project/ansible/inventory.txt
                echo "Our management instances are already configured."
            else
                echo "here else"
                cat ~/project/ansible/inventory.txt
                cd ansible
                ansible-playbook -i inventory.txt configure-server.yml
            fi

  configure-cluster:
    docker:
      - image: python:3.7-alpine3.17
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a3:83:19:0c:ff:be:6c:66:7b:9f:c4:3e:e2:d1:2e:08"
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            if grep -q "No changes to deploy" ~/project/ansible/checkIfDeployed.txt
            then
                cat ~/project/ansible/inventory.txt
                echo "Our management instances are already configured."
            else
                cat ~/project/ansible/inventory.txt
                cd ansible
                ansible-playbook -i inventory.txt configure-cluster.yml
            fi
      - run:
          name: Wait for LoadBalancer's domain to become reachable
          command: |
            if grep -q "No changes to deploy" ~/project/ansible/checkIfDeployed.txt
            then
                cat ~/project/ansible/inventory.txt
                echo "Our management instances are already configured."
            else
                cat ~/project/ansible/inventory.txt
                echo "Wait 60 seconds..."
                sleep 60
            fi
      - run:
          name: Display the LoadBalancer's DNS name
          command: |
            cat ~/project/ansible/inventory.txt
            cd ansible
            ansible-playbook -i inventory.txt save-elb-dns.yml
            touch ~/elb_dns.txt
            cat ~/elb_dns.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - elb_dns.txt

  deploy-docker:
    docker:
      - image: python:3.7-alpine3.17
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a3:83:19:0c:ff:be:6c:66:7b:9f:c4:3e:e2:d1:2e:08"
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Deploy Docker Image
          command: |
            cat ~/project/ansible/inventory.txt
            cd ansible
            ansible-playbook -i inventory.txt deploy-app.yml
          no_output_timeout: 2m

workflows:
  default:
    jobs:
      - test-build
      - upload-docker:
          requires:
            - test-build
          filters:
            branches:
              only: [main]
      - deploy-infrastructure:
          filters:
            branches:
              only: [main]
      - configure-infrastructure:
          requires:
            - deploy-infrastructure
      - configure-cluster:
          requires:
            - configure-infrastructure
            - upload-docker
      - deploy-docker:
          requires:
            - configure-cluster
